"""
AI Code Review Agent (Multi-Agent)
====================================
Reviews pull requests using parallel specialist agents:
  - Security agent: checks for vulnerabilities and unsafe patterns
  - Performance agent: spots inefficiencies and bottlenecks
  - Style agent: reviews naming, structure, and readability
  - Orchestrator: synthesises all findings into a final review

Setup:
    pip install -r requirements.txt
    export OPENAI_API_KEY=sk-...
    export GITHUB_TOKEN=ghp_...
    python agent.py --repo owner/repo --pr 42

Output: A structured Markdown review posted as a PR comment.
"""

import argparse
import asyncio
import os

import httpx
from openai import AsyncOpenAI

client = AsyncOpenAI()
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
MODEL = "gpt-4o"


# ── GitHub helpers ────────────────────────────────────────────

async def get_pr_diff(owner: str, repo: str, pr_number: int) -> str:
    async with httpx.AsyncClient() as http:
        resp = await http.get(
            f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}",
            headers={
                "Authorization": f"Bearer {GITHUB_TOKEN}",
                "Accept": "application/vnd.github.diff",
            },
        )
        resp.raise_for_status()
        return resp.text


async def post_review_comment(owner: str, repo: str, pr_number: int, body: str):
    async with httpx.AsyncClient() as http:
        resp = await http.post(
            f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments",
            headers={
                "Authorization": f"Bearer {GITHUB_TOKEN}",
                "Accept": "application/vnd.github+json",
            },
            json={"body": body},
        )
        resp.raise_for_status()
    return resp.json().get("html_url", "")


# ── Specialist agents ─────────────────────────────────────────

async def run_specialist(role: str, focus: str, diff: str) -> str:
    system = (
        f"You are a {role} code reviewer. "
        f"Focus only on {focus}. "
        "Be concise. Format findings as a bullet list. "
        "If there are no issues, say 'No issues found.'"
    )
    response = await client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": f"Review this diff:\n\n{diff[:6000]}"},
        ],
        temperature=0.2,
    )
    return response.choices[0].message.content


async def run_orchestrator(security: str, performance: str, style: str) -> str:
    system = (
        "You are a senior engineer synthesising three code review reports "
        "into one final review. Be constructive, prioritise critical issues, "
        "and end with an overall assessment: APPROVE, REQUEST_CHANGES, or COMMENT."
    )
    combined = (
        f"## Security Review\n{security}\n\n"
        f"## Performance Review\n{performance}\n\n"
        f"## Style Review\n{style}"
    )
    response = await client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": combined},
        ],
        temperature=0.3,
    )
    return response.choices[0].message.content


# ── Main orchestration ────────────────────────────────────────

async def review_pr(owner: str, repo: str, pr_number: int, post: bool = False):
    print(f"Fetching diff for {owner}/{repo}#{pr_number}...")
    diff = await get_pr_diff(owner, repo, pr_number)

    print("Running specialist agents in parallel...")
    security, performance, style = await asyncio.gather(
        run_specialist("security", "SQL injection, secrets, unsafe inputs, auth issues", diff),
        run_specialist("performance", "N+1 queries, memory leaks, inefficient loops, blocking calls", diff),
        run_specialist("style", "naming conventions, function length, code duplication, readability", diff),
    )

    print("Synthesising final review...")
    final_review = await run_orchestrator(security, performance, style)

    review_body = (
        f"## AI Code Review\n\n"
        f"<details><summary>Security findings</summary>\n\n{security}\n\n</details>\n\n"
        f"<details><summary>Performance findings</summary>\n\n{performance}\n\n</details>\n\n"
        f"<details><summary>Style findings</summary>\n\n{style}\n\n</details>\n\n"
        f"---\n\n### Final Assessment\n\n{final_review}\n\n"
        f"*Generated by ai-code-review-agent*"
    )

    print("\n" + "="*60)
    print(review_body)

    if post and GITHUB_TOKEN:
        url = await post_review_comment(owner, repo, pr_number, review_body)
        print(f"\nPosted review: {url}")
    else:
        print("\n(Use --post flag to post this as a GitHub comment)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="AI Code Review Agent")
    parser.add_argument("--repo", required=True, help="owner/repo")
    parser.add_argument("--pr", required=True, type=int, help="PR number")
    parser.add_argument("--post", action="store_true", help="Post review to GitHub")
    args = parser.parse_args()

    owner, repo = args.repo.split("/")
    asyncio.run(review_pr(owner, repo, args.pr, post=args.post))
